version: '3.8'

services:
  wireai-frontend:
    container_name: wireai-frontend
    image: wireai-frontend-image
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3030:3000
    restart: always
    entrypoint: serve -s build
    
  # wireai-backend: 
  #   container_name: wireai-backend
  #   image: postgres:17.2-alpine3.20
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: rootPass
  #     POSTGRES_DB: publications
  #   volumes:
  #     - ./publications.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - 5412:5432