CREATE TABLE "locations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city" varchar(50) NOT NULL,
  "state" varchar(50) DEFAULT null,
  "country" varchar(50) NOT NULL
);

CREATE TABLE "dois" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prefix" varchar(6) NOT NULL,
  "suffix" varchar(255) NOT NULL
);

CREATE TABLE "conferences" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booktitle" varchar(255) NOT NULL,
  "booktitle_short" varchar(10) NOT NULL,
  "publisher" varchar(255) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "location" int NOT NULL
);

CREATE TABLE "conference_papers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "conference" int NOT NULL,
  "start_page" int DEFAULT null,
  "end_page" int DEFAULT null,
  "doi" int DEFAULT null
);

CREATE TABLE "journals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "journal" varchar(255) NOT NULL,
  "journal_short" varchar(10) NOT NULL,
  "publisher" varchar(255) NOT NULL
);

CREATE TABLE "journal_papers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "journal" int NOT NULL,
  "volume" int DEFAULT null,
  "number" int DEFAULT null,
  "start_page" int DEFAULT null,
  "end_page" int DEFAULT null,
  "year" date NOT NULL,
  "doi" int DEFAULT null
);

CREATE TABLE "publications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conf_id" int,
  "jour_id" int
);

CREATE TABLE "authors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "publication_id" int NOT NULL,
  "researcher_id" int NOT NULL,
  "index" int NOT NULL
);

CREATE TABLE "organizations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "affiliations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "department" varchar(255) NOT NULL,
  "organization" int NOT NULL,
  "location" int NOT NULL
);

CREATE TABLE "researchers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "middle_name" varchar(50) DEFAULT null,
  "last_name" varchar(50) NOT NULL,
  "email" varchar(255) NOT NULL,
  "affiliation" int NOT NULL,
  "bio" varchar(255) NOT NULL
);

ALTER TABLE "conferences" ADD FOREIGN KEY ("location") REFERENCES "locations" ("id");

ALTER TABLE "conference_papers" ADD FOREIGN KEY ("conference") REFERENCES "conferences" ("id");

ALTER TABLE "conference_papers" ADD FOREIGN KEY ("doi") REFERENCES "dois" ("id");

ALTER TABLE "journal_papers" ADD FOREIGN KEY ("journal") REFERENCES "journals" ("id");

ALTER TABLE "journal_papers" ADD FOREIGN KEY ("doi") REFERENCES "dois" ("id");

ALTER TABLE "publications" ADD FOREIGN KEY ("conf_id") REFERENCES "conference_papers" ("id");

ALTER TABLE "publications" ADD FOREIGN KEY ("jour_id") REFERENCES "journal_papers" ("id");

ALTER TABLE "authors" ADD FOREIGN KEY ("publication_id") REFERENCES "publications" ("id");

ALTER TABLE "authors" ADD FOREIGN KEY ("researcher_id") REFERENCES "researchers" ("id");

ALTER TABLE "affiliations" ADD FOREIGN KEY ("organization") REFERENCES "organizations" ("id");

ALTER TABLE "affiliations" ADD FOREIGN KEY ("location") REFERENCES "locations" ("id");

ALTER TABLE "researchers" ADD FOREIGN KEY ("affiliation") REFERENCES "affiliations" ("id");
